### ISSUE TITLE
Issue using the dapp through alpha.aragon.one

### ISSUE THREAD

**Issue by fubuloubu** [aragon/aragon-core#157]
So I've started an Aragon org (address [0x5f1D61e4dB9E92d9B637CdEFcc098Edc521684b7](https://ropsten.etherscan.io/address/0x5f1D61e4dB9E92d9B637CdEFcc098Edc521684b7) on ropsten). I can't actually make changes to the organization. I was curious if I was having a problem with integration (although the dapp found my address from Metamask so it seemed okay). My address is  [0x9ccfe84b0ca911566bca31862fa13073bdac0e52](https://ropsten.etherscan.io/address/0x9ccfe84b0ca911566bca31862fa13073bdac0e52) on ropsten.

One other thought I was having is that perhaps it was because I didn't own any shares (no address does on init it seems) so no changes can be made? Perhaps the originating owner should get 1 share (100% ownership) when setting up the organization, and they can create and disperse shares unilaterally after that.

Along that same vein, say someone wants to port an existing organization to Aragon, perhaps there should be a secondary deployment option where a list of up to 5-10 shareholders (whatever might make sense) and corresponding shares is provided to bootstrap the org. They can vote to add the rest of shareholders later, preventing unilateral decisions from the get-go.

I'm not actively using the demo, just very interested in the idea. Let me know!

**Comment by izqui** [comment]
The organization wasn't fully initialized. The creation process involves 2 transactions and from what i see in your address, you only made one (not your fault, an issue with the client). 

The current version in development will present users with multiple organization templates for bootstrapping different types of organizations. 

Using the current version of the client with Kovan instead of Ropsten is much more reliable.

Closing the issue here as we use this repo just for smart contract development, but if you have more questions you can come talk to us at the [Aragon chat](https://aragon.chat) or submit an issue to the [issues repo](https://github.com/aragon/issues/issues).

**Comment by fubuloubu** [comment]
Thanks for answering @izqui!

Out of curiosity, what makes it work better on kovan? I've used ropsten and rinkeby, but I don't know much about kovan

**Comment by izqui** [comment]
Kovan has 4 second block times so the overall experience is much better :)
