### ISSUE TITLE
Required solidity version

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-core#158]
By requiring a fixed solidity version in all `aragon-core` files, we are forcing all app developers to use the same solidity version, which right now is set to `0.4.15`.

At least we should allow `0.4` versions greater than `15` by changing it to `^0.4.15`.

**Comment by sohkai** [comment]
Hmm, I'm not a huge fan of this idea. Pinning solidity versions is usually a security recommendation, because you never know what might be wrong with a new `solc`.

We could manually update the version as new `solc` versions are released, after at least running the tests.

-----------

> we are forcing all app developers to use the same solidity version

Are we? AFAIK app developers are free to use whatever version they want. If there's a problem with interfaces that we provide, then we should separate those out into different files and only apply loose versions on them.

**Comment by izqui** [comment]
That’s a good point actually. Strict versions on core logic and loose
versions on interfaces.
