### ISSUE TITLE
Linter crash on assembly blocks

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-core#62]
As outlined in #59:

```
An error occurred while running the linter on /home/quazia/Sites/quazia/aragon-core/contracts/kernel/Kernel.sol:
Error: An error occured while parsing the source code:
SyntaxError: Expected "=:", "hex", "let", "{", "}", comment, end of line, number, string, or whitespace but "r" found. Line: 108, Column: 17
```

**Comment by izqui** [comment]
Found error was related to assembly returns not being supported. Apparently this was fixed one month ago but the npm repo hasn't been updated. Created issue https://github.com/ConsenSys/solidity-parser/issues/90

**Comment by duaraghav8** [comment]
Hi @izqui, @Quazia, I stumbled upon this codebase :)
I maintain solium. solidity-parser hasn't been updated and that is an issue. But its not what caused this error.

Solium currently relies on duaraghav8/solparse for solidity parsing. It is a **fork** of solidity-parser (I forked because SP not being updated was blocking my releases). solparse went slightly out of sync with SP and that's why assembly parsing caused an error.

But its fixed now. Please update solium and let me know if the error still persists.
Thanks for (unknowingly!) reporting this issue.

**Comment by izqui** [comment]
Oh, thanks so much for fixing it :)

Gotta love open source serendipity!
